spring:
  application:
    name: notification_service

  rabbitmq:
    host: ${HOSPITAL_APP_RABBITMQ_HOST}
    port: ${HOSPITAL_APP_RABBITMQ_PORT}
    username: ${HOSPITAL_APP_RABBITMQ_USER}
    password: ${HOSPITAL_APP_RABBITMQ_PASS}
    ssl:
      enabled: ${HOSPITAL_APP_RABBITMQ_SSL_ENABLED}
      algorithm: ${HOSPITAL_APP_RABBITMQ_SSL_ALGO}
      validate-server-certificate: ${HOSPITAL_APP_RABBITMQ_SSL_VALIDATE}
      key-store: ${HOSPITAL_APP_RABBITMQ_KEYSTORE}
      key-store-password: ${HOSPITAL_APP_RABBITMQ_KEYSTORE_PASS}
      trust-store: ${HOSPITAL_APP_RABBITMQ_TRUSTSTORE}
      trust-store-password: ${HOSPITAL_APP_RABBITMQ_TRUSTSTORE_PASS}

  datasource:
    url: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_URL}
    username: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_USER}
    password: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_PASS}
    driver-class-name: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DIALECT}
    show-sql: true

  mail:
    host: ${HOSPITAL_APP_NOTIFICATION_SERVICE_MAIL_HOST}
    port: ${HOSPITAL_APP_NOTIFICATION_SERVICE_MAIL_PORT}
    username: ${HOSPITAL_APP_NOTIFICATION_SERVICE_MAIL_USER}
    password: ${HOSPITAL_APP_NOTIFICATION_SERVICE_MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

resilience4j:
  retry:
    instances:
      emailRetry:
        max-attempts: 3
        wait-duration: 30s
        exponential-backoff-multiplier: 2.0
        retry-exceptions:
          - java.lang.Exception
