spring:
  application:
    name: notification_service

  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest

  datasource:
    url: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_URL}
    username: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_USER}
    password: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_PASS}
    driver-class-name: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DIALECT}
    show-sql: true
