spring:
  application:
    name: notification_service

  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest

  datasource:
    url: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_URL}
    username: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_USER}
    password: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_PASS}
    driver-class-name: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${HOSPITAL_APP_NOTIFICATION_SERVICE_DB_DIALECT}
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gabrieldears@gmail.com
    password: xzqp btbu torv hehk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

resilience4j:
  retry:
    instances:
      emailRetry:
        max-attempts: 3          # Retry 3 times
        wait-duration: 30s       # Wait 30 seconds between retries
        exponential-backoff-multiplier: 2.0  # Optional: increase wait exponentially
        retry-exceptions:
          - java.lang.Exception  # Retry on any exception

